package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 公式取值条件.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiFormulaDefRule implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主建. */
	private String id;

	/** 条件. */
	private String condition;

	/** 参数条件(前). */
	private String front;

	/** 函数名称. */
	private String funName;

	/** 对比值(后). */
	private String back;

	/** 创建时间. */
	private String createTime;

	/** 筛选结果. */
	private BiScreeningResults biScreeningResults;

	/**
	 * Constructor.
	 */
	public BiFormulaDefRule() {
	}

	/**
	 * Set the 主建.
	 * 
	 * @param id
	 *            主建
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 主建.
	 * 
	 * @return 主建
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 条件.
	 * 
	 * @param condition
	 *            条件
	 */
	public void setCondition(String condition) {
		this.condition = condition;
	}

	/**
	 * Get the 条件.
	 * 
	 * @return 条件
	 */
	public String getCondition() {
		return this.condition;
	}

	/**
	 * Set the 参数条件(前).
	 * 
	 * @param front
	 *            参数条件(前)
	 */
	public void setFront(String front) {
		this.front = front;
	}

	/**
	 * Get the 参数条件(前).
	 * 
	 * @return 参数条件(前)
	 */
	public String getFront() {
		return this.front;
	}

	/**
	 * Set the 函数名称.
	 * 
	 * @param funName
	 *            函数名称
	 */
	public void setFunName(String funName) {
		this.funName = funName;
	}

	/**
	 * Get the 函数名称.
	 * 
	 * @return 函数名称
	 */
	public String getFunName() {
		return this.funName;
	}

	/**
	 * Set the 对比值(后).
	 * 
	 * @param back
	 *            对比值(后)
	 */
	public void setBack(String back) {
		this.back = back;
	}

	/**
	 * Get the 对比值(后).
	 * 
	 * @return 对比值(后)
	 */
	public String getBack() {
		return this.back;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 筛选结果.
	 * 
	 * @param biScreeningResults
	 *            筛选结果
	 */
	public void setBiScreeningResults(BiScreeningResults biScreeningResults) {
		this.biScreeningResults = biScreeningResults;
	}

	/**
	 * Get the 筛选结果.
	 * 
	 * @return 筛选结果
	 */
	public BiScreeningResults getBiScreeningResults() {
		return this.biScreeningResults;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiFormulaDefRule other = (BiFormulaDefRule) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
