package com.cn.hsd.rm.formula.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 公式定义.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiFormulaDef implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 公式主建. */
	private String formulaDefId;

	/** 说明. */
	private String remark;

	/** 创建时间. */
	private String createTime;

	/** 更新时间. */
	private String updateTime;

	/** 更新用户. */
	private String updateUser;

	/** 有效性. */
	private String expiry;

	/** 开始时间. */
	private String startTime;

	/** 结束时间. */
	private String endDate;

	/** 风险要素. */
	private BiRiskFactors biRiskFactors;

	/** The set of 风险识别规则. */
	private Set<BiRiskRules> biRiskRulesSet;

	/**
	 * Constructor.
	 */
	public BiFormulaDef() {
		this.biRiskRulesSet = new HashSet<BiRiskRules>();
	}

	/**
	 * Set the 公式主建.
	 * 
	 * @param formulaDefId
	 *            公式主建
	 */
	public void setFormulaDefId(String formulaDefId) {
		this.formulaDefId = formulaDefId;
	}

	/**
	 * Get the 公式主建.
	 * 
	 * @return 公式主建
	 */
	public String getFormulaDefId() {
		return this.formulaDefId;
	}

	/**
	 * Set the 说明.
	 * 
	 * @param remark
	 *            说明
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * Get the 说明.
	 * 
	 * @return 说明
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateTime
	 *            更新时间
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public String getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the 更新用户.
	 * 
	 * @param updateUser
	 *            更新用户
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * Get the 更新用户.
	 * 
	 * @return 更新用户
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}

	/**
	 * Set the 有效性.
	 * 
	 * @param expiry
	 *            有效性
	 */
	public void setExpiry(String expiry) {
		this.expiry = expiry;
	}

	/**
	 * Get the 有效性.
	 * 
	 * @return 有效性
	 */
	public String getExpiry() {
		return this.expiry;
	}

	/**
	 * Set the 开始时间.
	 * 
	 * @param startTime
	 *            开始时间
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * Get the 开始时间.
	 * 
	 * @return 开始时间
	 */
	public String getStartTime() {
		return this.startTime;
	}

	/**
	 * Set the 结束时间.
	 * 
	 * @param endDate
	 *            结束时间
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * Get the 结束时间.
	 * 
	 * @return 结束时间
	 */
	public String getEndDate() {
		return this.endDate;
	}

	/**
	 * Set the 风险要素.
	 * 
	 * @param biRiskFactors
	 *            风险要素
	 */
	public void setBiRiskFactors(BiRiskFactors biRiskFactors) {
		this.biRiskFactors = biRiskFactors;
	}

	/**
	 * Get the 风险要素.
	 * 
	 * @return 风险要素
	 */
	public BiRiskFactors getBiRiskFactors() {
		return this.biRiskFactors;
	}

	/**
	 * Set the set of the 风险识别规则.
	 * 
	 * @param biRiskRulesSet
	 *            The set of 风险识别规则
	 */
	public void setBiRiskRulesSet(Set<BiRiskRules> biRiskRulesSet) {
		this.biRiskRulesSet = biRiskRulesSet;
	}

	/**
	 * Add the 风险识别规则.
	 * 
	 * @param biRiskRules
	 *            风险识别规则
	 */
	public void addBiRiskRules(BiRiskRules biRiskRules) {
		this.biRiskRulesSet.add(biRiskRules);
	}

	/**
	 * Get the set of the 风险识别规则.
	 * 
	 * @return The set of 风险识别规则
	 */
	public Set<BiRiskRules> getBiRiskRulesSet() {
		return this.biRiskRulesSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((formulaDefId == null) ? 0 : formulaDefId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiFormulaDef other = (BiFormulaDef) obj;
		if (formulaDefId == null) {
			if (other.formulaDefId != null) {
				return false;
			}
		} else if (!formulaDefId.equals(other.formulaDefId)) {
			return false;
		}
		return true;
	}

}
