package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 指标定义.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiQuotaDef implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 指标定义ID. */
	private String quotaDefId;

	/** 表名. */
	private String tableName;

	/** 字段名称. */
	private String fieldName;

	/** 字段中文名称. */
	private String fieldNameCn;

	/** 创建时间. */
	private String createTime;

	/**
	 * Constructor.
	 */
	public BiQuotaDef() {
	}

	/**
	 * Set the 指标定义ID.
	 * 
	 * @param quotaDefId
	 *            指标定义ID
	 */
	public void setQuotaDefId(String quotaDefId) {
		this.quotaDefId = quotaDefId;
	}

	/**
	 * Get the 指标定义ID.
	 * 
	 * @return 指标定义ID
	 */
	public String getQuotaDefId() {
		return this.quotaDefId;
	}

	/**
	 * Set the 表名.
	 * 
	 * @param tableName
	 *            表名
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * Get the 表名.
	 * 
	 * @return 表名
	 */
	public String getTableName() {
		return this.tableName;
	}

	/**
	 * Set the 字段名称.
	 * 
	 * @param fieldName
	 *            字段名称
	 */
	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	/**
	 * Get the 字段名称.
	 * 
	 * @return 字段名称
	 */
	public String getFieldName() {
		return this.fieldName;
	}

	/**
	 * Set the 字段中文名称.
	 * 
	 * @param fieldNameCn
	 *            字段中文名称
	 */
	public void setFieldNameCn(String fieldNameCn) {
		this.fieldNameCn = fieldNameCn;
	}

	/**
	 * Get the 字段中文名称.
	 * 
	 * @return 字段中文名称
	 */
	public String getFieldNameCn() {
		return this.fieldNameCn;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((quotaDefId == null) ? 0 : quotaDefId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiQuotaDef other = (BiQuotaDef) obj;
		if (quotaDefId == null) {
			if (other.quotaDefId != null) {
				return false;
			}
		} else if (!quotaDefId.equals(other.quotaDefId)) {
			return false;
		}
		return true;
	}

}
