package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 指标分类.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiQuotaType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private String id;

	/** 表名. */
	private String tableName;

	/** 类别中文名. */
	private String tableNameCn;

	/**
	 * Constructor.
	 */
	public BiQuotaType() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param id
	 *            主键
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 表名.
	 * 
	 * @param tableName
	 *            表名
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * Get the 表名.
	 * 
	 * @return 表名
	 */
	public String getTableName() {
		return this.tableName;
	}

	/**
	 * Set the 类别中文名.
	 * 
	 * @param tableNameCn
	 *            类别中文名
	 */
	public void setTableNameCn(String tableNameCn) {
		this.tableNameCn = tableNameCn;
	}

	/**
	 * Get the 类别中文名.
	 * 
	 * @return 类别中文名
	 */
	public String getTableNameCn() {
		return this.tableNameCn;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiQuotaType other = (BiQuotaType) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
