package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 指标定义参考值.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiQuotaData implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** TABLE_NAME. */
	private String tableName;

	/** 字段. */
	private String field;

	/** KEY. */
	private String key;

	/** NAME_CN. */
	private String nameCn;

	/** 排序值. */
	private String val;

	/**
	 * Constructor.
	 */
	public BiQuotaData() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the TABLE_NAME.
	 * 
	 * @param tableName
	 *            TABLE_NAME
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * Get the TABLE_NAME.
	 * 
	 * @return TABLE_NAME
	 */
	public String getTableName() {
		return this.tableName;
	}

	/**
	 * Set the 字段.
	 * 
	 * @param field
	 *            字段
	 */
	public void setField(String field) {
		this.field = field;
	}

	/**
	 * Get the 字段.
	 * 
	 * @return 字段
	 */
	public String getField() {
		return this.field;
	}

	/**
	 * Set the KEY.
	 * 
	 * @param key
	 *            KEY
	 */
	public void setKey(String key) {
		this.key = key;
	}

	/**
	 * Get the KEY.
	 * 
	 * @return KEY
	 */
	public String getKey() {
		return this.key;
	}

	/**
	 * Set the NAME_CN.
	 * 
	 * @param nameCn
	 *            NAME_CN
	 */
	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}

	/**
	 * Get the NAME_CN.
	 * 
	 * @return NAME_CN
	 */
	public String getNameCn() {
		return this.nameCn;
	}

	/**
	 * Set the 排序值.
	 * 
	 * @param val
	 *            排序值
	 */
	public void setVal(String val) {
		this.val = val;
	}

	/**
	 * Get the 排序值.
	 * 
	 * @return 排序值
	 */
	public String getVal() {
		return this.val;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiQuotaData other = (BiQuotaData) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
