package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 风险等级结果表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiResultData implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主建. */
	private String id;

	/** 计算日期. */
	private String reckonDate;

	/** 航班编号. */
	private String fltNo;

	/** 计算结果. */
	private String result;

	/** 风险等级结果. */
	private String riskGrade;

	/** 创建时间. */
	private String createTime;

	/** 风险要素. */
	private BiRiskFactors biRiskFactors;

	/**
	 * Constructor.
	 */
	public BiResultData() {
	}

	/**
	 * Set the 主建.
	 * 
	 * @param id
	 *            主建
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 主建.
	 * 
	 * @return 主建
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 计算日期.
	 * 
	 * @param reckonDate
	 *            计算日期
	 */
	public void setReckonDate(String reckonDate) {
		this.reckonDate = reckonDate;
	}

	/**
	 * Get the 计算日期.
	 * 
	 * @return 计算日期
	 */
	public String getReckonDate() {
		return this.reckonDate;
	}

	/**
	 * Set the 航班编号.
	 * 
	 * @param fltNo
	 *            航班编号
	 */
	public void setFltNo(String fltNo) {
		this.fltNo = fltNo;
	}

	/**
	 * Get the 航班编号.
	 * 
	 * @return 航班编号
	 */
	public String getFltNo() {
		return this.fltNo;
	}

	/**
	 * Set the 计算结果.
	 * 
	 * @param result
	 *            计算结果
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * Get the 计算结果.
	 * 
	 * @return 计算结果
	 */
	public String getResult() {
		return this.result;
	}

	/**
	 * Set the 风险等级结果.
	 * 
	 * @param riskGrade
	 *            风险等级结果
	 */
	public void setRiskGrade(String riskGrade) {
		this.riskGrade = riskGrade;
	}

	/**
	 * Get the 风险等级结果.
	 * 
	 * @return 风险等级结果
	 */
	public String getRiskGrade() {
		return this.riskGrade;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 风险要素.
	 * 
	 * @param biRiskFactors
	 *            风险要素
	 */
	public void setBiRiskFactors(BiRiskFactors biRiskFactors) {
		this.biRiskFactors = biRiskFactors;
	}

	/**
	 * Get the 风险要素.
	 * 
	 * @return 风险要素
	 */
	public BiRiskFactors getBiRiskFactors() {
		return this.biRiskFactors;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiResultData other = (BiResultData) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
