package com.cn.hsd.rm.formula.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 风险识别规则.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiRiskRules implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 规则ID. */
	private String rulesId;

	/** 值. */
	private String value;

	/** 值类型. */
	private String valueType;

	/** 关系. */
	private String relation;

	/** 措施. */
	private String measures;

	/** 公式定义. */
	private BiFormulaDef biFormulaDef;

	/** The set of 筛选结果. */
	private Set<BiScreeningResults> biScreeningResultsSet;

	/**
	 * Constructor.
	 */
	public BiRiskRules() {
		this.biScreeningResultsSet = new HashSet<BiScreeningResults>();
	}

	/**
	 * Set the 规则ID.
	 * 
	 * @param rulesId
	 *            规则ID
	 */
	public void setRulesId(String rulesId) {
		this.rulesId = rulesId;
	}

	/**
	 * Get the 规则ID.
	 * 
	 * @return 规则ID
	 */
	public String getRulesId() {
		return this.rulesId;
	}

	/**
	 * Set the 值.
	 * 
	 * @param value
	 *            值
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Get the 值.
	 * 
	 * @return 值
	 */
	public String getValue() {
		return this.value;
	}

	/**
	 * Set the 值类型.
	 * 
	 * @param valueType
	 *            值类型
	 */
	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	/**
	 * Get the 值类型.
	 * 
	 * @return 值类型
	 */
	public String getValueType() {
		return this.valueType;
	}

	/**
	 * Set the 关系.
	 * 
	 * @param relation
	 *            关系
	 */
	public void setRelation(String relation) {
		this.relation = relation;
	}

	/**
	 * Get the 关系.
	 * 
	 * @return 关系
	 */
	public String getRelation() {
		return this.relation;
	}

	/**
	 * Set the 措施.
	 * 
	 * @param measures
	 *            措施
	 */
	public void setMeasures(String measures) {
		this.measures = measures;
	}

	/**
	 * Get the 措施.
	 * 
	 * @return 措施
	 */
	public String getMeasures() {
		return this.measures;
	}

	/**
	 * Set the 公式定义.
	 * 
	 * @param biFormulaDef
	 *            公式定义
	 */
	public void setBiFormulaDef(BiFormulaDef biFormulaDef) {
		this.biFormulaDef = biFormulaDef;
	}

	/**
	 * Get the 公式定义.
	 * 
	 * @return 公式定义
	 */
	public BiFormulaDef getBiFormulaDef() {
		return this.biFormulaDef;
	}

	/**
	 * Set the set of the 筛选结果.
	 * 
	 * @param biScreeningResultsSet
	 *            The set of 筛选结果
	 */
	public void setBiScreeningResultsSet(Set<BiScreeningResults> biScreeningResultsSet) {
		this.biScreeningResultsSet = biScreeningResultsSet;
	}

	/**
	 * Add the 筛选结果.
	 * 
	 * @param biScreeningResults
	 *            筛选结果
	 */
	public void addBiScreeningResults(BiScreeningResults biScreeningResults) {
		this.biScreeningResultsSet.add(biScreeningResults);
	}

	/**
	 * Get the set of the 筛选结果.
	 * 
	 * @return The set of 筛选结果
	 */
	public Set<BiScreeningResults> getBiScreeningResultsSet() {
		return this.biScreeningResultsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rulesId == null) ? 0 : rulesId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiRiskRules other = (BiRiskRules) obj;
		if (rulesId == null) {
			if (other.rulesId != null) {
				return false;
			}
		} else if (!rulesId.equals(other.rulesId)) {
			return false;
		}
		return true;
	}

}
