package com.cn.hsd.rm.formula.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 风险要素.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiRiskFactors implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 风险要素主建. */
	private String riskId;

	/** 父ID. */
	private String pid;

	/** 名称. */
	private String name;

	/** 创建时间. */
	private String createTime;

	/** 是否为终端要素. */
	private Short isEndNode;

	/** 子节点个数. */
	private Integer childNodeNumber;

	/** The set of 公式定义. */
	private Set<BiFormulaDef> biFormulaDefSet;

	/** The set of 风险等级结果表. */
	private Set<BiResultData> biResultDataSet;

	/** The set of 风险要素等级表. */
	private Set<BiRiskFactorsLevel> biRiskFactorsLevelSet;

	/** The set of 终端分类关系表. */
	private Set<BiTerminalTypeRef> biTerminalTypeRefSet;

	/** The set of 风险矩阵. */
	private Set<Matrix> matrixSet;

	/**
	 * Constructor.
	 */
	public BiRiskFactors() {
		this.biFormulaDefSet = new HashSet<BiFormulaDef>();
		this.biResultDataSet = new HashSet<BiResultData>();
		this.biRiskFactorsLevelSet = new HashSet<BiRiskFactorsLevel>();
		this.biTerminalTypeRefSet = new HashSet<BiTerminalTypeRef>();
		this.matrixSet = new HashSet<Matrix>();
	}

	/**
	 * Set the 风险要素主建.
	 * 
	 * @param riskId
	 *            风险要素主建
	 */
	public void setRiskId(String riskId) {
		this.riskId = riskId;
	}

	/**
	 * Get the 风险要素主建.
	 * 
	 * @return 风险要素主建
	 */
	public String getRiskId() {
		return this.riskId;
	}

	/**
	 * Set the 父ID.
	 * 
	 * @param pid
	 *            父ID
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * Get the 父ID.
	 * 
	 * @return 父ID
	 */
	public String getPid() {
		return this.pid;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 是否为终端要素.
	 * 
	 * @param isEndNode
	 *            是否为终端要素
	 */
	public void setIsEndNode(Short isEndNode) {
		this.isEndNode = isEndNode;
	}

	/**
	 * Get the 是否为终端要素.
	 * 
	 * @return 是否为终端要素
	 */
	public Short getIsEndNode() {
		return this.isEndNode;
	}

	/**
	 * Set the 子节点个数.
	 * 
	 * @param childNodeNumber
	 *            子节点个数
	 */
	public void setChildNodeNumber(Integer childNodeNumber) {
		this.childNodeNumber = childNodeNumber;
	}

	/**
	 * Get the 子节点个数.
	 * 
	 * @return 子节点个数
	 */
	public Integer getChildNodeNumber() {
		return this.childNodeNumber;
	}

	/**
	 * Set the set of the 公式定义.
	 * 
	 * @param biFormulaDefSet
	 *            The set of 公式定义
	 */
	public void setBiFormulaDefSet(Set<BiFormulaDef> biFormulaDefSet) {
		this.biFormulaDefSet = biFormulaDefSet;
	}

	/**
	 * Add the 公式定义.
	 * 
	 * @param biFormulaDef
	 *            公式定义
	 */
	public void addBiFormulaDef(BiFormulaDef biFormulaDef) {
		this.biFormulaDefSet.add(biFormulaDef);
	}

	/**
	 * Get the set of the 公式定义.
	 * 
	 * @return The set of 公式定义
	 */
	public Set<BiFormulaDef> getBiFormulaDefSet() {
		return this.biFormulaDefSet;
	}

	/**
	 * Set the set of the 风险等级结果表.
	 * 
	 * @param biResultDataSet
	 *            The set of 风险等级结果表
	 */
	public void setBiResultDataSet(Set<BiResultData> biResultDataSet) {
		this.biResultDataSet = biResultDataSet;
	}

	/**
	 * Add the 风险等级结果表.
	 * 
	 * @param biResultData
	 *            风险等级结果表
	 */
	public void addBiResultData(BiResultData biResultData) {
		this.biResultDataSet.add(biResultData);
	}

	/**
	 * Get the set of the 风险等级结果表.
	 * 
	 * @return The set of 风险等级结果表
	 */
	public Set<BiResultData> getBiResultDataSet() {
		return this.biResultDataSet;
	}

	/**
	 * Set the set of the 风险要素等级表.
	 * 
	 * @param biRiskFactorsLevelSet
	 *            The set of 风险要素等级表
	 */
	public void setBiRiskFactorsLevelSet(Set<BiRiskFactorsLevel> biRiskFactorsLevelSet) {
		this.biRiskFactorsLevelSet = biRiskFactorsLevelSet;
	}

	/**
	 * Add the 风险要素等级表.
	 * 
	 * @param biRiskFactorsLevel
	 *            风险要素等级表
	 */
	public void addBiRiskFactorsLevel(BiRiskFactorsLevel biRiskFactorsLevel) {
		this.biRiskFactorsLevelSet.add(biRiskFactorsLevel);
	}

	/**
	 * Get the set of the 风险要素等级表.
	 * 
	 * @return The set of 风险要素等级表
	 */
	public Set<BiRiskFactorsLevel> getBiRiskFactorsLevelSet() {
		return this.biRiskFactorsLevelSet;
	}

	/**
	 * Set the set of the 终端分类关系表.
	 * 
	 * @param biTerminalTypeRefSet
	 *            The set of 终端分类关系表
	 */
	public void setBiTerminalTypeRefSet(Set<BiTerminalTypeRef> biTerminalTypeRefSet) {
		this.biTerminalTypeRefSet = biTerminalTypeRefSet;
	}

	/**
	 * Add the 终端分类关系表.
	 * 
	 * @param biTerminalTypeRef
	 *            终端分类关系表
	 */
	public void addBiTerminalTypeRef(BiTerminalTypeRef biTerminalTypeRef) {
		this.biTerminalTypeRefSet.add(biTerminalTypeRef);
	}

	/**
	 * Get the set of the 终端分类关系表.
	 * 
	 * @return The set of 终端分类关系表
	 */
	public Set<BiTerminalTypeRef> getBiTerminalTypeRefSet() {
		return this.biTerminalTypeRefSet;
	}

	/**
	 * Set the set of the 风险矩阵.
	 * 
	 * @param matrixSet
	 *            The set of 风险矩阵
	 */
	public void setMatrixSet(Set<Matrix> matrixSet) {
		this.matrixSet = matrixSet;
	}

	/**
	 * Add the 风险矩阵.
	 * 
	 * @param matrix
	 *            风险矩阵
	 */
	public void addMatrix(Matrix matrix) {
		this.matrixSet.add(matrix);
	}

	/**
	 * Get the set of the 风险矩阵.
	 * 
	 * @return The set of 风险矩阵
	 */
	public Set<Matrix> getMatrixSet() {
		return this.matrixSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((riskId == null) ? 0 : riskId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiRiskFactors other = (BiRiskFactors) obj;
		if (riskId == null) {
			if (other.riskId != null) {
				return false;
			}
		} else if (!riskId.equals(other.riskId)) {
			return false;
		}
		return true;
	}

}
