package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 风险要素等级表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiRiskFactorsLevel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private String id;

	/** 等级标识（1：低，2：中，3：高）. */
	private Short levelFlag;

	/** 各个等级的值. */
	private Double levelValue;

	/** 风险要素. */
	private BiRiskFactors biRiskFactors;

	/**
	 * Constructor.
	 */
	public BiRiskFactorsLevel() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param id
	 *            主键
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 等级标识（1：低，2：中，3：高）.
	 * 
	 * @param levelFlag
	 *            等级标识（1：低，2：中，3：高）
	 */
	public void setLevelFlag(Short levelFlag) {
		this.levelFlag = levelFlag;
	}

	/**
	 * Get the 等级标识（1：低，2：中，3：高）.
	 * 
	 * @return 等级标识（1：低，2：中，3：高）
	 */
	public Short getLevelFlag() {
		return this.levelFlag;
	}

	/**
	 * Set the 各个等级的值.
	 * 
	 * @param levelValue
	 *            各个等级的值
	 */
	public void setLevelValue(Double levelValue) {
		this.levelValue = levelValue;
	}

	/**
	 * Get the 各个等级的值.
	 * 
	 * @return 各个等级的值
	 */
	public Double getLevelValue() {
		return this.levelValue;
	}

	/**
	 * Set the 风险要素.
	 * 
	 * @param biRiskFactors
	 *            风险要素
	 */
	public void setBiRiskFactors(BiRiskFactors biRiskFactors) {
		this.biRiskFactors = biRiskFactors;
	}

	/**
	 * Get the 风险要素.
	 * 
	 * @return 风险要素
	 */
	public BiRiskFactors getBiRiskFactors() {
		return this.biRiskFactors;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiRiskFactorsLevel other = (BiRiskFactorsLevel) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
