package com.cn.hsd.rm.formula.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 筛选结果.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiScreeningResults implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 项主建. */
	private String itemId;

	/** 关系. */
	private String nexus;

	/** 是否为符号. */
	private String isSign;

	/** 表名. */
	private String tableName;

	/** 字段名称. */
	private String field;

	/** 函数或排序. */
	private String fun;

	/** 对比条件. */
	private String contrast;

	/** BACK_TYPE. */
	private String backType;

	/** BACK. */
	private String back;

	/** 序号. */
	private Short orderNum;

	/** 风险识别规则. */
	private BiRiskRules biRiskRules;

	/** The set of 公式取值条件. */
	private Set<BiFormulaDefRule> biFormulaDefRuleSet;

	/**
	 * Constructor.
	 */
	public BiScreeningResults() {
		this.biFormulaDefRuleSet = new HashSet<BiFormulaDefRule>();
	}

	/**
	 * Set the 项主建.
	 * 
	 * @param itemId
	 *            项主建
	 */
	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	/**
	 * Get the 项主建.
	 * 
	 * @return 项主建
	 */
	public String getItemId() {
		return this.itemId;
	}

	/**
	 * Set the 关系.
	 * 
	 * @param nexus
	 *            关系
	 */
	public void setNexus(String nexus) {
		this.nexus = nexus;
	}

	/**
	 * Get the 关系.
	 * 
	 * @return 关系
	 */
	public String getNexus() {
		return this.nexus;
	}

	/**
	 * Set the 是否为符号.
	 * 
	 * @param isSign
	 *            是否为符号
	 */
	public void setIsSign(String isSign) {
		this.isSign = isSign;
	}

	/**
	 * Get the 是否为符号.
	 * 
	 * @return 是否为符号
	 */
	public String getIsSign() {
		return this.isSign;
	}

	/**
	 * Set the 表名.
	 * 
	 * @param tableName
	 *            表名
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * Get the 表名.
	 * 
	 * @return 表名
	 */
	public String getTableName() {
		return this.tableName;
	}

	/**
	 * Set the 字段名称.
	 * 
	 * @param field
	 *            字段名称
	 */
	public void setField(String field) {
		this.field = field;
	}

	/**
	 * Get the 字段名称.
	 * 
	 * @return 字段名称
	 */
	public String getField() {
		return this.field;
	}

	/**
	 * Set the 函数或排序.
	 * 
	 * @param fun
	 *            函数或排序
	 */
	public void setFun(String fun) {
		this.fun = fun;
	}

	/**
	 * Get the 函数或排序.
	 * 
	 * @return 函数或排序
	 */
	public String getFun() {
		return this.fun;
	}

	/**
	 * Set the 对比条件.
	 * 
	 * @param contrast
	 *            对比条件
	 */
	public void setContrast(String contrast) {
		this.contrast = contrast;
	}

	/**
	 * Get the 对比条件.
	 * 
	 * @return 对比条件
	 */
	public String getContrast() {
		return this.contrast;
	}

	/**
	 * Set the BACK_TYPE.
	 * 
	 * @param backType
	 *            BACK_TYPE
	 */
	public void setBackType(String backType) {
		this.backType = backType;
	}

	/**
	 * Get the BACK_TYPE.
	 * 
	 * @return BACK_TYPE
	 */
	public String getBackType() {
		return this.backType;
	}

	/**
	 * Set the BACK.
	 * 
	 * @param back
	 *            BACK
	 */
	public void setBack(String back) {
		this.back = back;
	}

	/**
	 * Get the BACK.
	 * 
	 * @return BACK
	 */
	public String getBack() {
		return this.back;
	}

	/**
	 * Set the 序号.
	 * 
	 * @param orderNum
	 *            序号
	 */
	public void setOrderNum(Short orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * Get the 序号.
	 * 
	 * @return 序号
	 */
	public Short getOrderNum() {
		return this.orderNum;
	}

	/**
	 * Set the 风险识别规则.
	 * 
	 * @param biRiskRules
	 *            风险识别规则
	 */
	public void setBiRiskRules(BiRiskRules biRiskRules) {
		this.biRiskRules = biRiskRules;
	}

	/**
	 * Get the 风险识别规则.
	 * 
	 * @return 风险识别规则
	 */
	public BiRiskRules getBiRiskRules() {
		return this.biRiskRules;
	}

	/**
	 * Set the set of the 公式取值条件.
	 * 
	 * @param biFormulaDefRuleSet
	 *            The set of 公式取值条件
	 */
	public void setBiFormulaDefRuleSet(Set<BiFormulaDefRule> biFormulaDefRuleSet) {
		this.biFormulaDefRuleSet = biFormulaDefRuleSet;
	}

	/**
	 * Add the 公式取值条件.
	 * 
	 * @param biFormulaDefRule
	 *            公式取值条件
	 */
	public void addBiFormulaDefRule(BiFormulaDefRule biFormulaDefRule) {
		this.biFormulaDefRuleSet.add(biFormulaDefRule);
	}

	/**
	 * Get the set of the 公式取值条件.
	 * 
	 * @return The set of 公式取值条件
	 */
	public Set<BiFormulaDefRule> getBiFormulaDefRuleSet() {
		return this.biFormulaDefRuleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiScreeningResults other = (BiScreeningResults) obj;
		if (itemId == null) {
			if (other.itemId != null) {
				return false;
			}
		} else if (!itemId.equals(other.itemId)) {
			return false;
		}
		return true;
	}

}
