package com.cn.hsd.rm.formula.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 终端分类.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BiTerminalType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 类别ID. */
	private String terminalTypeId;

	/** 名称. */
	private String name;

	/** 父ID. */
	private String pid;

	/** 创建时间. */
	private String createTime;

	/** The set of 终端分类关系表. */
	private Set<BiTerminalTypeRef> biTerminalTypeRefSet;

	/**
	 * Constructor.
	 */
	public BiTerminalType() {
		this.biTerminalTypeRefSet = new HashSet<BiTerminalTypeRef>();
	}

	/**
	 * Set the 类别ID.
	 * 
	 * @param terminalTypeId
	 *            类别ID
	 */
	public void setTerminalTypeId(String terminalTypeId) {
		this.terminalTypeId = terminalTypeId;
	}

	/**
	 * Get the 类别ID.
	 * 
	 * @return 类别ID
	 */
	public String getTerminalTypeId() {
		return this.terminalTypeId;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 父ID.
	 * 
	 * @param pid
	 *            父ID
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * Get the 父ID.
	 * 
	 * @return 父ID
	 */
	public String getPid() {
		return this.pid;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the set of the 终端分类关系表.
	 * 
	 * @param biTerminalTypeRefSet
	 *            The set of 终端分类关系表
	 */
	public void setBiTerminalTypeRefSet(Set<BiTerminalTypeRef> biTerminalTypeRefSet) {
		this.biTerminalTypeRefSet = biTerminalTypeRefSet;
	}

	/**
	 * Add the 终端分类关系表.
	 * 
	 * @param biTerminalTypeRef
	 *            终端分类关系表
	 */
	public void addBiTerminalTypeRef(BiTerminalTypeRef biTerminalTypeRef) {
		this.biTerminalTypeRefSet.add(biTerminalTypeRef);
	}

	/**
	 * Get the set of the 终端分类关系表.
	 * 
	 * @return The set of 终端分类关系表
	 */
	public Set<BiTerminalTypeRef> getBiTerminalTypeRefSet() {
		return this.biTerminalTypeRefSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((terminalTypeId == null) ? 0 : terminalTypeId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BiTerminalType other = (BiTerminalType) obj;
		if (terminalTypeId == null) {
			if (other.terminalTypeId != null) {
				return false;
			}
		} else if (!terminalTypeId.equals(other.terminalTypeId)) {
			return false;
		}
		return true;
	}

}
