package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 航班飞行员表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FlightPilot implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主建. */
	private String id;

	/** 航班主键. */
	private String fltId;

	/** 飞行员ID. */
	private String pilotId;

	/** 创建时间. */
	private String createTime;

	/**
	 * Constructor.
	 */
	public FlightPilot() {
	}

	/**
	 * Set the 主建.
	 * 
	 * @param id
	 *            主建
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 主建.
	 * 
	 * @return 主建
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 航班主键.
	 * 
	 * @param fltId
	 *            航班主键
	 */
	public void setFltId(String fltId) {
		this.fltId = fltId;
	}

	/**
	 * Get the 航班主键.
	 * 
	 * @return 航班主键
	 */
	public String getFltId() {
		return this.fltId;
	}

	/**
	 * Set the 飞行员ID.
	 * 
	 * @param pilotId
	 *            飞行员ID
	 */
	public void setPilotId(String pilotId) {
		this.pilotId = pilotId;
	}

	/**
	 * Get the 飞行员ID.
	 * 
	 * @return 飞行员ID
	 */
	public String getPilotId() {
		return this.pilotId;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FlightPilot other = (FlightPilot) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
