package com.cn.hsd.rm.formula.model;

import java.io.Serializable;

/**
 * Model class of 航班.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Flight implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 航班主键. */
	private String id;

	/** 航班号. */
	private String fltNo;

	/** 是否国际航班. */
	private String isInternational;

	/** 起飞机场. */
	private String startAirport;

	/** 降落机场. */
	private String endAirport;

	/** 计飞：计划起飞时间. */
	private String startTime;

	/** 预飞：预计起飞时间. */
	private String realStartTime;

	/** 实飞：实际起飞时间. */
	private String departureTime;

	/** 预达：预计到达时间. */
	private String realEndTime;

	/** 计达：计划降落时间. */
	private String endTime;

	/** 实达：实际降落时间. */
	private String arrivalTime;

	/** 签派放行时间. */
	private String dispatchDate;

	/** 局方是否批复. */
	private String isApprove;

	/** 是否备降过. */
	private String isBak;

	/** 开舱门时间. */
	private String openDoorDate;

	/** 关舱门时间. */
	private String closeDoorDate;

	/** 创建时间. */
	private String createTime;

	/** 是否变更航班. */
	private String isChange;

	/**
	 * Constructor.
	 */
	public Flight() {
	}

	/**
	 * Set the 航班主键.
	 * 
	 * @param id
	 *            航班主键
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 航班主键.
	 * 
	 * @return 航班主键
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 航班号.
	 * 
	 * @param fltNo
	 *            航班号
	 */
	public void setFltNo(String fltNo) {
		this.fltNo = fltNo;
	}

	/**
	 * Get the 航班号.
	 * 
	 * @return 航班号
	 */
	public String getFltNo() {
		return this.fltNo;
	}

	/**
	 * Set the 是否国际航班.
	 * 
	 * @param isInternational
	 *            是否国际航班
	 */
	public void setIsInternational(String isInternational) {
		this.isInternational = isInternational;
	}

	/**
	 * Get the 是否国际航班.
	 * 
	 * @return 是否国际航班
	 */
	public String getIsInternational() {
		return this.isInternational;
	}

	/**
	 * Set the 起飞机场.
	 * 
	 * @param startAirport
	 *            起飞机场
	 */
	public void setStartAirport(String startAirport) {
		this.startAirport = startAirport;
	}

	/**
	 * Get the 起飞机场.
	 * 
	 * @return 起飞机场
	 */
	public String getStartAirport() {
		return this.startAirport;
	}

	/**
	 * Set the 降落机场.
	 * 
	 * @param endAirport
	 *            降落机场
	 */
	public void setEndAirport(String endAirport) {
		this.endAirport = endAirport;
	}

	/**
	 * Get the 降落机场.
	 * 
	 * @return 降落机场
	 */
	public String getEndAirport() {
		return this.endAirport;
	}

	/**
	 * Set the 计飞：计划起飞时间.
	 * 
	 * @param startTime
	 *            计飞：计划起飞时间
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * Get the 计飞：计划起飞时间.
	 * 
	 * @return 计飞：计划起飞时间
	 */
	public String getStartTime() {
		return this.startTime;
	}

	/**
	 * Set the 预飞：预计起飞时间.
	 * 
	 * @param realStartTime
	 *            预飞：预计起飞时间
	 */
	public void setRealStartTime(String realStartTime) {
		this.realStartTime = realStartTime;
	}

	/**
	 * Get the 预飞：预计起飞时间.
	 * 
	 * @return 预飞：预计起飞时间
	 */
	public String getRealStartTime() {
		return this.realStartTime;
	}

	/**
	 * Set the 实飞：实际起飞时间.
	 * 
	 * @param departureTime
	 *            实飞：实际起飞时间
	 */
	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime;
	}

	/**
	 * Get the 实飞：实际起飞时间.
	 * 
	 * @return 实飞：实际起飞时间
	 */
	public String getDepartureTime() {
		return this.departureTime;
	}

	/**
	 * Set the 预达：预计到达时间.
	 * 
	 * @param realEndTime
	 *            预达：预计到达时间
	 */
	public void setRealEndTime(String realEndTime) {
		this.realEndTime = realEndTime;
	}

	/**
	 * Get the 预达：预计到达时间.
	 * 
	 * @return 预达：预计到达时间
	 */
	public String getRealEndTime() {
		return this.realEndTime;
	}

	/**
	 * Set the 计达：计划降落时间.
	 * 
	 * @param endTime
	 *            计达：计划降落时间
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * Get the 计达：计划降落时间.
	 * 
	 * @return 计达：计划降落时间
	 */
	public String getEndTime() {
		return this.endTime;
	}

	/**
	 * Set the 实达：实际降落时间.
	 * 
	 * @param arrivalTime
	 *            实达：实际降落时间
	 */
	public void setArrivalTime(String arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	/**
	 * Get the 实达：实际降落时间.
	 * 
	 * @return 实达：实际降落时间
	 */
	public String getArrivalTime() {
		return this.arrivalTime;
	}

	/**
	 * Set the 签派放行时间.
	 * 
	 * @param dispatchDate
	 *            签派放行时间
	 */
	public void setDispatchDate(String dispatchDate) {
		this.dispatchDate = dispatchDate;
	}

	/**
	 * Get the 签派放行时间.
	 * 
	 * @return 签派放行时间
	 */
	public String getDispatchDate() {
		return this.dispatchDate;
	}

	/**
	 * Set the 局方是否批复.
	 * 
	 * @param isApprove
	 *            局方是否批复
	 */
	public void setIsApprove(String isApprove) {
		this.isApprove = isApprove;
	}

	/**
	 * Get the 局方是否批复.
	 * 
	 * @return 局方是否批复
	 */
	public String getIsApprove() {
		return this.isApprove;
	}

	/**
	 * Set the 是否备降过.
	 * 
	 * @param isBak
	 *            是否备降过
	 */
	public void setIsBak(String isBak) {
		this.isBak = isBak;
	}

	/**
	 * Get the 是否备降过.
	 * 
	 * @return 是否备降过
	 */
	public String getIsBak() {
		return this.isBak;
	}

	/**
	 * Set the 开舱门时间.
	 * 
	 * @param openDoorDate
	 *            开舱门时间
	 */
	public void setOpenDoorDate(String openDoorDate) {
		this.openDoorDate = openDoorDate;
	}

	/**
	 * Get the 开舱门时间.
	 * 
	 * @return 开舱门时间
	 */
	public String getOpenDoorDate() {
		return this.openDoorDate;
	}

	/**
	 * Set the 关舱门时间.
	 * 
	 * @param closeDoorDate
	 *            关舱门时间
	 */
	public void setCloseDoorDate(String closeDoorDate) {
		this.closeDoorDate = closeDoorDate;
	}

	/**
	 * Get the 关舱门时间.
	 * 
	 * @return 关舱门时间
	 */
	public String getCloseDoorDate() {
		return this.closeDoorDate;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 是否变更航班.
	 * 
	 * @param isChange
	 *            是否变更航班
	 */
	public void setIsChange(String isChange) {
		this.isChange = isChange;
	}

	/**
	 * Get the 是否变更航班.
	 * 
	 * @return 是否变更航班
	 */
	public String getIsChange() {
		return this.isChange;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Flight other = (Flight) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
