package com.cn.hsd.rm.formula.model;

import java.io.Serializable;
import java.sql.Blob;

/**
 * Model class of 飞行员表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Pilots implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 飞行员ID. */
	private String pilotsId;

	/** 飞行员名称. */
	private String name;

	/** 飞行员编号. */
	private String empNum;

	/** 执照ID. */
	private String licenseId;

	/** ICAO英语等级. */
	private String icaolevel;

	/** ICAO证书颁发时间. */
	private String icaostartdate;

	/** 国籍. */
	private String nationality;

	/** 城市. */
	private String cityid;

	/** 身份证号. */
	private String idCardno;

	/** 英文名. */
	private String enName;

	/** 心理压力. */
	private String mentalStress;

	/** 生日. */
	private Blob birthday;

	/** 应急训练颁发日期. */
	private String emergencyStartdate;

	/** 最后休息时间. */
	private String lastBreakTime;

	/** 飞行员健康状况. */
	private String pilotHealth;

	/** 技术等级. */
	private String technicalGrade;

	/**
	 * Constructor.
	 */
	public Pilots() {
	}

	/**
	 * Set the 飞行员ID.
	 * 
	 * @param pilotsId
	 *            飞行员ID
	 */
	public void setPilotsId(String pilotsId) {
		this.pilotsId = pilotsId;
	}

	/**
	 * Get the 飞行员ID.
	 * 
	 * @return 飞行员ID
	 */
	public String getPilotsId() {
		return this.pilotsId;
	}

	/**
	 * Set the 飞行员名称.
	 * 
	 * @param name
	 *            飞行员名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 飞行员名称.
	 * 
	 * @return 飞行员名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 飞行员编号.
	 * 
	 * @param empNum
	 *            飞行员编号
	 */
	public void setEmpNum(String empNum) {
		this.empNum = empNum;
	}

	/**
	 * Get the 飞行员编号.
	 * 
	 * @return 飞行员编号
	 */
	public String getEmpNum() {
		return this.empNum;
	}

	/**
	 * Set the 执照ID.
	 * 
	 * @param licenseId
	 *            执照ID
	 */
	public void setLicenseId(String licenseId) {
		this.licenseId = licenseId;
	}

	/**
	 * Get the 执照ID.
	 * 
	 * @return 执照ID
	 */
	public String getLicenseId() {
		return this.licenseId;
	}

	/**
	 * Set the ICAO英语等级.
	 * 
	 * @param icaolevel
	 *            ICAO英语等级
	 */
	public void setIcaolevel(String icaolevel) {
		this.icaolevel = icaolevel;
	}

	/**
	 * Get the ICAO英语等级.
	 * 
	 * @return ICAO英语等级
	 */
	public String getIcaolevel() {
		return this.icaolevel;
	}

	/**
	 * Set the ICAO证书颁发时间.
	 * 
	 * @param icaostartdate
	 *            ICAO证书颁发时间
	 */
	public void setIcaostartdate(String icaostartdate) {
		this.icaostartdate = icaostartdate;
	}

	/**
	 * Get the ICAO证书颁发时间.
	 * 
	 * @return ICAO证书颁发时间
	 */
	public String getIcaostartdate() {
		return this.icaostartdate;
	}

	/**
	 * Set the 国籍.
	 * 
	 * @param nationality
	 *            国籍
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	/**
	 * Get the 国籍.
	 * 
	 * @return 国籍
	 */
	public String getNationality() {
		return this.nationality;
	}

	/**
	 * Set the 城市.
	 * 
	 * @param cityid
	 *            城市
	 */
	public void setCityid(String cityid) {
		this.cityid = cityid;
	}

	/**
	 * Get the 城市.
	 * 
	 * @return 城市
	 */
	public String getCityid() {
		return this.cityid;
	}

	/**
	 * Set the 身份证号.
	 * 
	 * @param idCardno
	 *            身份证号
	 */
	public void setIdCardno(String idCardno) {
		this.idCardno = idCardno;
	}

	/**
	 * Get the 身份证号.
	 * 
	 * @return 身份证号
	 */
	public String getIdCardno() {
		return this.idCardno;
	}

	/**
	 * Set the 英文名.
	 * 
	 * @param enName
	 *            英文名
	 */
	public void setEnName(String enName) {
		this.enName = enName;
	}

	/**
	 * Get the 英文名.
	 * 
	 * @return 英文名
	 */
	public String getEnName() {
		return this.enName;
	}

	/**
	 * Set the 心理压力.
	 * 
	 * @param mentalStress
	 *            心理压力
	 */
	public void setMentalStress(String mentalStress) {
		this.mentalStress = mentalStress;
	}

	/**
	 * Get the 心理压力.
	 * 
	 * @return 心理压力
	 */
	public String getMentalStress() {
		return this.mentalStress;
	}

	/**
	 * Set the 生日.
	 * 
	 * @param birthday
	 *            生日
	 */
	public void setBirthday(Blob birthday) {
		this.birthday = birthday;
	}

	/**
	 * Get the 生日.
	 * 
	 * @return 生日
	 */
	public Blob getBirthday() {
		return this.birthday;
	}

	/**
	 * Set the 应急训练颁发日期.
	 * 
	 * @param emergencyStartdate
	 *            应急训练颁发日期
	 */
	public void setEmergencyStartdate(String emergencyStartdate) {
		this.emergencyStartdate = emergencyStartdate;
	}

	/**
	 * Get the 应急训练颁发日期.
	 * 
	 * @return 应急训练颁发日期
	 */
	public String getEmergencyStartdate() {
		return this.emergencyStartdate;
	}

	/**
	 * Set the 最后休息时间.
	 * 
	 * @param lastBreakTime
	 *            最后休息时间
	 */
	public void setLastBreakTime(String lastBreakTime) {
		this.lastBreakTime = lastBreakTime;
	}

	/**
	 * Get the 最后休息时间.
	 * 
	 * @return 最后休息时间
	 */
	public String getLastBreakTime() {
		return this.lastBreakTime;
	}

	/**
	 * Set the 飞行员健康状况.
	 * 
	 * @param pilotHealth
	 *            飞行员健康状况
	 */
	public void setPilotHealth(String pilotHealth) {
		this.pilotHealth = pilotHealth;
	}

	/**
	 * Get the 飞行员健康状况.
	 * 
	 * @return 飞行员健康状况
	 */
	public String getPilotHealth() {
		return this.pilotHealth;
	}

	/**
	 * Set the 技术等级.
	 * 
	 * @param technicalGrade
	 *            技术等级
	 */
	public void setTechnicalGrade(String technicalGrade) {
		this.technicalGrade = technicalGrade;
	}

	/**
	 * Get the 技术等级.
	 * 
	 * @return 技术等级
	 */
	public String getTechnicalGrade() {
		return this.technicalGrade;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pilotsId == null) ? 0 : pilotsId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Pilots other = (Pilots) obj;
		if (pilotsId == null) {
			if (other.pilotsId != null) {
				return false;
			}
		} else if (!pilotsId.equals(other.pilotsId)) {
			return false;
		}
		return true;
	}

}
