SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS AIRPORT;
DROP TABLE IF EXISTS FLIGHT;
DROP TABLE IF EXISTS PILOTS;
DROP TABLE IF EXISTS PLANE;




/* Create Tables */

CREATE TABLE AIRPORT
(
	FLIGHT_ID char(32) NOT NULL,
	RUNWAY_LENGTH int,
	MARK_HEIGHT int,
	DEVICE varchar(32),
	SPECIAL_PROGRAM varchar(32),
	G_VISIBILITY int,
	G_VISIBILITY_STD int,
	CLOUD_HIGH int,
	CLOUD_HIGH_STD int,
	BUMP_VAL int,
	WEATHER_CON varchar(32),
	LINE_ATTR_TYPE varchar(32),
	AIRPROT_ATTR_TYPE varchar(32),
	CREW_ATTR_TYPE varchar(32),
	CAPT_CREW_ATTR_TYPE varchar(32),
	COP_CREW_ATTR_TYPE varchar(32),
	DOWN_AIRPORT_ATTR_TYPE varchar(32),
	AIRPORT varchar(32),
	DOWN_LIGHT_UNITS varchar(32),
	DOWN_AIRPROT_UNITS varchar(8),
	SLOPE varchar(8),
	TEMPERATURE int,
	RVR_TG int,
	RVR_TD_STD int,
	VISIBILITY_TG int,
	VISIBILITY_TG_STD int,
	DOWN_SIDE_WIND_AVG int,
	DOWN_SIDE_WIND_FIT int,
	DOWN_TAIL_WIND_AVG int,
	DOWN_TAIL_WIND_FIT int,
	UP_SIDE_WIND_AVG int,
	UP_SIDE_WIND_FIT int,
	PRIMARY KEY (FLIGHT_ID)
);


CREATE TABLE FLIGHT
(
	ID char(32) NOT NULL,
	FLT_NO varchar(16),
	IS_INTERNATIONAL varchar(8),
	START_AIRPORT varchar(32),
	END_AIRPORT varchar(32),
	START_TIME varchar(32),
	REAL_START_TIME varchar(32),
	DEPARTURE_TIME varchar(32),
	REAL_END_TIME varchar(32),
	END_TIME varchar(32),
	ARRIVAL_TIME varchar(32),
	TGC varchar(32),
	START_TIME_SHORT varchar(8),
	END_TIME_SHORT varchar(8),
	ROUTE_CHANGE int,
	PRIMARY KEY (ID)
);


CREATE TABLE PILOTS
(
	ID char(32) NOT NULL,
	-- A,B,C
	CAPT_HEALTH_GRADE char COMMENT 'A,B,C',
	-- C063是否飞行前休息全为夜间(机长)
	CAPT_REST_TIME varchar(8) COMMENT 'C063是否飞行前休息全为夜间(机长)',
	CAPT_REST_TIME_LENGTH int,
	CAPT_DUTY_START varchar(8),
	CAPT_DUTY_END varchar(8),
	CAPT_FLT_NUM int,
	CAPT_DUTY_NUM int,
	CAPT_WITH_ZERO int,
	CAPT_AGE int,
	CAPT_LVACA_NUM int,
	CAPT_SEVEN_FAT int,
	CAPT_MONTH_FAT int,
	CAPT_THREE_MONTH int,
	COP_HEALTH_GRADE char,
	COP_REST_TIME varchar(8),
	COP_REST_TIME_LENGTH int,
	COP_DUTY_END varchar(8),
	COP_DUTY_START varchar(8),
	COP_FLT_NUM int,
	COP_DUTY_NUM int,
	COP_WITH_ZERO int,
	COP_AGE int,
	COP_LVACA_NUM int,
	CAPT_LAYOUT_CHANGE int,
	COP_LAYOUT_CHANGE int,
	COP_SEVEN_FAT int,
	COP_MONTH_FAT int,
	COP_THREE_MONTH int,
	COP_AGE int,
	CAPT_LAST_AIRPORT int,
	CAPT_THREE_M_AIRPORT int,
	CAPT_LAST_FLT_TIME int,
	CAPT_FLT_EXP int,
	CAPT_LAST_TRAIN int,
	COP_LAST_TRAIN int,
	COP_FLT_EXP int,
	COP_LAST_FLT_TIME int,
	COP_LAST_AIRPORT int,
	CAPT_CREW_TYPE varchar(32),
	COP_CREW_TYPE varchar(32),
	COOP_DEGREE int,
	PRIMARY KEY (ID)
);


CREATE TABLE PLANE
(
	PLANE_ID char(32) NOT NULL,
	PLANE_NO varchar(8),
	MEL tinyint,
	VIP_TYPE tinyint,
	CHECK tinyint,
	ABN_FLIGHT tinyint,
	CHANGE_LINE tinyint,
	DANGEROUS_WEATHER tinyint,
	PCOUNT int,
	TGC varchar(32),
	MEL int,
	CDL int,
	AIRPORT char(8),
	PRIMARY KEY (PLANE_ID)
);



